### ISSUE TITLE
Xamarin - Keep Login

### ISSUE THREAD

**Issue by DomingoL** [DevExpress-Examples/XAF_Security_E4908#58]
Hi guys, thanks for the examples
I have a query about the example for xamarin, how can I keep the login once the user logs in and not ask for the login again every time the application is going to be used

**Comment by AndreyKozhevnikov** [comment]
Hello,

I created a separate ticket in our support center regarding this question: <a href="https://supportcenter.devexpress.com/internal/ticket/details/t967756">T967756 - How to save a user&apos;s credentials in the &apos;XAF_Security_E4908/XPO/Xamarin.Forms&apos; example</a>
I will answer there shortly.

Thanks,
Andrey

**Comment by kashiash** [comment]
can you make https://supportcenter.devexpress.com/internal/ticket/details/t967756 public ?
