### ISSUE TITLE
Please upgrade to v21.2.3

### ISSUE THREAD

**Issue by donhuvy** [DevExpress-Examples/XAF_Security_E4908#82]
I use branch 21.1 . I cannot run project now.

![image](https://user-images.githubusercontent.com/1328316/141112673-fc049d86-6b2e-482a-8cb8-589df78d4399.png)

**Comment by AlexanderZhyrkov** [comment]
Hello,

We usually update our examples once in a major version or when there are API changes. This example can be used with v21.2.3 as well.

To update this example to v21.2.3, use the Project Converter or other options listed at [Updating Packages](https://docs.devexpress.com/GeneralInformation/118420/installation/install-devexpress-controls-using-nuget-packages/updating-packages).

If you have additional questions, please submit a ticket to the [DevExpress Support Center](https://supportcenter.devexpress.com/ticket/list).
