### ISSUE TITLE
Utility of multiple RegisterEntity() calls

### ISSUE THREAD

**Issue by xavehoo** [DevExpress-Examples/XAF_Security_E4908#83]
Hi, in the XPO -> Console sample I don't understand the utility of the multiple calls to objectSpaceProvider.TypesInfo.RegisterEntity(); only one call (for example, the first: "xxx.RegisterEntity(typeof(Employee))") is needed for all objects to be "usable", or, at least, that's what happens when a I created a similar sample.

**Comment by AndreyKozhevnikov** [comment]
Hello,

Please create a ticket in our <a href="https://supportcenter.devexpress.com/ticket/list?preset=mytickets">Support Center</a> and ask your question there. We'll be happy to assist you.

Thanks,
Andrey
